Update GitHub Actions config

diff --git a/.github/workflows/wf-branch-development.yml b/.github/workflows/wf-branch-development.yml
--- a/.github/workflows/wf-branch-development.yml
+++ b/.github/workflows/wf-branch-development.yml
@@ -36,13 +36,15 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Verify Environment Variables
-        if: ("${{ env.ANCESTORS_LIST }}" == "" || "${{ env.API_VERSION }}" == "" || "${{ env.API_VERSION_COSMWASM }}" == "" || "${{ env.BACKEND }}" == "" || "${{ env.BACKEND_WS }}" == "" || "${{ env.CONTRACT_DEX}}" == "" || "${{ env.FIRST_CONVERSION_RATE }}" == "" || "${{ env.FIRST_HEIGHT }}" == "" || "${{ env.HAS_POOLS }}" == "" || "${{ env.LCD_URL }}" == "" || "${{ env.MAIN_TITLE }}" == "" || "${{ env.WASM_CW20_CODE_ID }}" == "" || "${{ env.WASM_SWAP_CODE_ID }}" == "" || "${{ env.WS_URL }}" == "")
         run: |
-          echo "Error: Environment variables are not set."
-          exit 1
+          if ("${{ env.ANCESTORS_LIST }}" == "" || "${{ env.API_VERSION }}" == "" || "${{ env.API_VERSION_COSMWASM }}" == "" || "${{ env.BACKEND }}" == "" || "${{ env.BACKEND_WS }}" == "" || "${{ env.CONTRACT_DEX }}" == "" || "${{ env.FIRST_CONVERSION_RATE }}" == "" || "${{ env.FIRST_HEIGHT }}" == ""  || "${{ env.HAS_POOLS }}" == "" || "${{ env.LCD_URL }}" == "" || "${{ env.MAIN_TITLE }}" == "" || "${{ env.WASM_CW20_CODE_ID }}" == "" || "${{ env.WASM_SWAP_CODE_ID }}" == "" || "${{ env.WS_URL }}" == ""); then
+            echo "Error: one or more environment variables are not set."
+            exit 1
+          else
+            echo "Environment variables are set."
+          fi
 
       - name: Set up Docker Buildx
-        if: ${{ success() }}
         uses: docker/setup-buildx-action@v3
 
       - name: Login To Registry
